// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhd87bAuSzbdIJ8WPBSdq6RhL9L0LZlAs',
    appId: '1:884214702233:web:0195c283723bfada931808',
    messagingSenderId: '884214702233',
    projectId: 'fasum-app-523b2',
    authDomain: 'fasum-app-523b2.firebaseapp.com',
    storageBucket: 'fasum-app-523b2.firebasestorage.app',
    measurementId: 'G-FXF1BVL4NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ5vo8T1o2YaEos0smPZLGlV8QekX8OiM',
    appId: '1:884214702233:android:eadaa36aeac6f6bd931808',
    messagingSenderId: '884214702233',
    projectId: 'fasum-app-523b2',
    storageBucket: 'fasum-app-523b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkGeZlizuEHIVoLSHdol8huyj0Fmerpc4',
    appId: '1:884214702233:ios:02546f3a3d94a6ae931808',
    messagingSenderId: '884214702233',
    projectId: 'fasum-app-523b2',
    storageBucket: 'fasum-app-523b2.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkGeZlizuEHIVoLSHdol8huyj0Fmerpc4',
    appId: '1:884214702233:ios:02546f3a3d94a6ae931808',
    messagingSenderId: '884214702233',
    projectId: 'fasum-app-523b2',
    storageBucket: 'fasum-app-523b2.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhd87bAuSzbdIJ8WPBSdq6RhL9L0LZlAs',
    appId: '1:884214702233:web:18715072ffd61434931808',
    messagingSenderId: '884214702233',
    projectId: 'fasum-app-523b2',
    authDomain: 'fasum-app-523b2.firebaseapp.com',
    storageBucket: 'fasum-app-523b2.firebasestorage.app',
    measurementId: 'G-K2JPVL9K7X',
  );
}
